// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    var addHistory, doc, enlarge, formatDate, formatTimestamp, id, iframe, loadVideo, pad, shrink, video, videoContent, wrapper;
    shrink = $('#videoSize #shrink');
    enlarge = $('#videoSize #enlarge');
    video = $('#video');
    videoContent = $('#videoContent');
    wrapper = $('#wrapper');
    iframe = $('#iframe')[0];
    pad = function(num) {
      var s;
      s = num + "";
      while (s.length < 2) {
        s = "0" + s;
      }
      return s;
    };
    $.fn.scrollView = function(quick) {
      var duration;
      duration = 1000;
      if ((quick != null) === true) {
        duration = 10;
      }
      return this.each(function() {
        return $('html, body').animate({
          scrollTop: $(this).offset().top
        }, duration);
      });
    };
    $('form').ajaxForm({
      data: {
        src: 'ajax'
      },
      success: function(responseText, statusText, xhr, $form) {
        var r;
        if (!responseText) {
          return alert('No response, is the url correct?');
        } else {
          r = $.parseJSON(responseText);
          addHistory(r);
          return loadVideo(r);
        }
      }
    });
    formatDate = function(timestamp, showSeconds) {
      var d, res;
      d = new Date(timestamp * 1000);
      return res = d.getFullYear() + '-' + pad(d.getMonth()) + '-' + pad(d.getDate());
    };
    formatTimestamp = function(timestamp, showSeconds) {
      var d, res;
      d = new Date(timestamp * 1000);
      res = pad(d.getDate()) + '-' + pad(d.getMonth()) + '-' + d.getFullYear() + ' @ ' + d.getHours() + ':' + pad(d.getMinutes());
      if ((showSeconds != null)) {
        res = res + ':' + pad(d.getSeconds());
      }
      return res;
    };
    addHistory = function(doc) {
      var aired, historyContent, historyItem, historyLink, historyList, timestamp;
      historyList = $('#historyList');
      historyItem = $('<li/>');
      aired = formatTimestamp(doc.Aired);
      timestamp = formatTimestamp(doc.Timestamp, true);
      historyLink = $('<a/>', {
        href: '?id=' + doc._id.$id
      });
      historyLink.html(timestamp + ' &mdash; ' + doc.Title);
      historyLink.click(function(e) {
        e.preventDefault();
        return loadVideo(doc);
      });
      historyLink.appendTo(historyItem);
      historyContent = $('<p/>');
      historyContent.html('Title: ' + doc.Title + '<br/> Aired: ' + aired + '<br/> Length: ' + doc.Duration);
      historyContent.appendTo(historyLink);
      return historyList.prepend(historyItem);
    };
    if (typeof collection !== "undefined" && collection !== null) {
      for (id in collection) {
        doc = collection[id];
        addHistory(doc);
      }
    }
    loadVideo = function(doc) {
      var aired, fileName, l, src, u, v, _i, _len, _ref;
      video.show();
      v = $('#video video')[0];
      if (doc.videoUrls != null) {
        _ref = doc.videoUrls;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          u = _ref[_i];
          if (u.mimeType === 'video/mp4') {
            src = u.Location;
          }
        }
        if (!src) {
          src = doc.videoUrls[0].Location;
        }
        l = $('#video a#download');
        l.attr('href', src);
        aired = formatDate(doc.Aired);
        fileName = (aired + '-' + doc.Title).replace(' ', '_') + '.mp4';
        l.attr('download', fileName);
        l.html('Download ' + fileName);
        v.src = src;
        v.load();
        return video.scrollView();
      } else {
        return alert('Something has gone tits up..');
      }
    };
    if (typeof collegeramaDocument !== "undefined" && collegeramaDocument !== null) {
      loadVideo($.parseJSON(collegeramaDocument));
    }
    $(videoSize).click(function(e) {
      e.preventDefault();
      if (shrink.css('display') === 'none') {
        shrink.css('display', 'block');
        enlarge.css('display', 'none');
        $('section[id!=video]').css('display', 'none');
        videoContent.css({
          position: 'absolute'
        });
        return $('#video h1').css({
          padding: '.2em .2em 0 .2em'
        });
      } else {
        shrink.css('display', 'none');
        enlarge.css('display', 'block');
        $('section[id!=video]').css('display', 'block');
        videoContent.css({
          position: 'relative'
        });
        $('#video h1').css({
          padding: 0
        });
        return video.scrollView(true);
      }
    });
    return $('#linksShow3mE').click(function(e) {
      e.preventDefault();
      $('#linksIframe').show().scrollView();
      return iframe.src = 'http://collegerama.tudelft.nl/Mediasite/Catalog/Full/cf028e9a2a244e1fbdb52ace3f9cd42d21';
    });
  });

}).call(this);
